all:         # All experiments must contain these fields
    - description
    - experiment
    - repositories:
        - P4Boosters
    - files:
        - documentation.md

memcached:   # Memcached must contain these in addition
    - files:
        - data
        - bitstream.tar.gz

e2e:
    - repositories:
        - TofinoP4Boosters
    - files:
        - data

fec:
    - files:
        - data
    - repositories:
        - TofinoP4Boosters
